### ISSUE TITLE
كنترل قيمت گذاري 

### ISSUE THREAD

**Issue by Rezaeian** [ehsmohammadi/Fuel-Management-Support#1]
![image](https://cloud.githubusercontent.com/assets/18718194/14948574/4c9a1dac-1057-11e6-9912-cc596677aa79.png)

Dear Mr. Hatefi
Please  Control Shahraz Vessel Inventory Operations.

**Comment by hatefi-arman** [comment]
Please inform me which part of data needs to be checked?

**Comment by ehsmohammadi** [comment]
عمليات قيمت گذاري كشتي شهراز براي حواله هاي شماره 5و7و8 با وجود امكان قيمت گذاري (قيمت دار بودن رسيدهاي خريد قبلي ) انجام نمي پذيرد لطفا بررسي هاي لازم انجام پذيرد 
![werwerw](https://cloud.githubusercontent.com/assets/3368702/14949424/240081d0-105f-11e6-8ec0-8b2d6f733b71.png)

**Comment by hatefi-arman** [comment]
تغییرات لازم اعمال گردید.
خواهشمند است جهت استفاده از دکمه های "قیمت گذاری" و "ایجاد اسناد"، حتماً فیلد "تا تاریخ" با مقدار مناسب (به طور نمونه 2015/6/30) جهت محدود سازی عملیات فوق مقداردهی گردد.
جهت انجام عملیات فوق ، **گزارشات سوخت** کشتی مربوطه مورد بررسی قرار گرفته و چنانچه رکوردی با مقادیر اصلاحی افزایشی و یا کاهشی پیدا شود که توسط **کارشناس مالی** مربوطه بازنگری و تأییده نشده است، پیغام خطایی که با آن مواجه شده اید، نمایش داده می شود. 
محدود سازی تاریخ، بررسی رکوردهایی که هنوز توسط مالی بررسی نشده اند را از دور عملیات خارج می سازد و قیمت گذاری و یا ایجاد اسناد بر روی رکورد های انبار تا تاریخ انتخابی اعمال می گردد.
![image](https://cloud.githubusercontent.com/assets/5567997/14953740/aa6504cc-1081-11e6-8af7-6657ceb5a0a2.png)
