### ISSUE TITLE
problem with record 74329

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#10]
خواهشمند است عمليات ثبت شده براي رديف 74329 برگشت داده شود و رديف مورد نظر لغو تائيد شود .
![asda](https://cloud.githubusercontent.com/assets/3368702/15153529/cbefb628-16ee-11e6-83aa-78bd95cbcc35.png)

**Comment by hatefi-arman** [comment]
احتراماً خواهشمند است موارد ذیل اعلام گردد:
1) علت برگشت این رکورد
2)  تغییرات قابل انجام بر روی این رکورد پس از برگشت آن
3) لیست تغییرات قابل اعمال بر روی رکوردهای بعدی

**Comment by Rezaeian** [comment]
اين ركورد به اشتباه انتقال داخلي ثبت شده در صورتيكه فروش انتقالي مي باشد
