### ISSUE TITLE
problem with parshan vessel Date 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#11]
با توجه به تغيير تاريخ سفر كشتي Parshan  خواهشمند است از تاريخ 31/0/2016 تا تاريخ 29/04/2016 شماره سفرهاي كشتي مورد نظر به BRD0090 تغيير يابد .

**Comment by hatefi-arman** [comment]
Done.
New SQL query written to perform this kind of task.
It had an inventory operation which reverted.
The type of EOV record changed to HeavingAnchor.
All the records Voyage Id updated.
The Voyage status in FMS changed to open.
The voyages in FMS updated from Rotation system.
Duration : 3:30'
