### ISSUE TITLE
All Vessels - Darvish - Sapid : Add new Fuel provider  

### ISSUE THREAD

**Issue by SaeidBarzegar** [ehsmohammadi/Fuel-Management-Support#112]
Mr.Darvish called and requests for adding a new chartere in system.

**Comment by ehsmohammadi** [comment]
I talked with Mr.Darvish about creating new provider in system , we must talk with Mr.Fateminia to arrange the needful action

**Comment by ehsmohammadi** [comment]
We must add new supplier with below information  : 
Title : National Iranian Oil Company 
Code : 0001719

**Comment by ehsmohammadi** [comment]
The company was added to the certain table
