### ISSUE TITLE
Negar - Ghanee - Hafez : ROD following 

### ISSUE THREAD

**Issue by SaeidBarzegar** [ehsmohammadi/Fuel-Management-Support#113]
Call Mr.Ghane(2816) and talk about Negar.

**Comment by ehsmohammadi** [comment]
I called Mr.ghane but he didn't answer the phone

**Comment by ehsmohammadi** [comment]
I called Mr.ghane but he didn't answer the phone

**Comment by ehsmohammadi** [comment]
I must call capt.Kazemi for solvin this ship problem , problem is not assigning voyage for Negar in lay up

**Comment by ehsmohammadi** [comment]
i called Mr.kazeminia for solve the problem, he didn't help on solving this matter then i talk about negar problem with captain zare  , he asked me for Letter No for following the problem and i found the letter

**Comment by ehsmohammadi** [comment]
follow my phone conversation with Capt,Zareee I tell him the letter No for follow our request to technical support ship manager

**Comment by ehsmohammadi** [comment]
Searching for lay up voyage number

**Comment by ehsmohammadi** [comment]
I insert a temporary voyage by myself and reordering the charter in and out after that i continue to confirm its event report instead of  ROD responsible person

**Comment by ehsmohammadi** [comment]
problem in confirming , big amount for correction seems to be bunkering event

**Comment by ehsmohammadi** [comment]
ROD following with getting DBN from vessel was completed , chartering item was inserted to system ,
all we need is Ms.Aghamohammadi   confirmation

**Comment by ehsmohammadi** [comment]
All thing in order now
