### ISSUE TITLE
Behshad - Seraj - Hafez : ROB problem

### ISSUE THREAD

**Issue by SaeidBarzegar** [ehsmohammadi/Fuel-Management-Support#114]
Arezoo and Behshad gave fuel from Beta and the sent report is not correct and we should edit it.

**Comment by ehsmohammadi** [comment]
Bunkering received in 2016-09-07 at 9:05 was transferred with below data from two vessels : 
Behta : transfer 96 ton fuel report to arezoo  
Behta : 3.569 to behshad 
Basht : 12.230

**Comment by ehsmohammadi** [comment]
Bunkering event report is split up   to two bunkering event report for behta and basht , the operation person add an internal order for each of them
