### ISSUE TITLE
Edit invoice has problem 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#13]
در زمان ايجاد و ويرايش صورت حساب در صورتيكه عامل تاثير گذار ، تسهيم پذير نمي باشد ، فيلد نوع تسهيم اجباري نيست و نيازي به انتخاب نوع آن نمي باشد .

**Comment by hatefi-arman** [comment]
- New rule checking added to both presentation and BL on adding non-division effective prices.
- New rule checking added to prevent creation of voucher for non-division effective factors with NO JournalEntry Segment settings at invoice creation, update, submit, and voucher register.
- UI enhancement for better manipulation of TotalDivisionPrice performed.
- TotalDivisionPrice column added to Invoice List.

Duration: 1 Day & 5 hours
