### ISSUE TITLE
Sequence Contain more than one element

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#14]
![mohammadi](https://cloud.githubusercontent.com/assets/3368702/15204061/c574910c-181e-11e6-869d-450cb0fdceb0.png)

Miss Aghamohamadi , Hafez company

**Comment by hatefi-arman** [comment]
The problem was at data level and is resolved.
The ActionDate field of entity workflow log prevented from changing when calling Deactivate() method on it.
Duration: 1:00
