### ISSUE TITLE
Closed and final Confirmed Order - Invoice problem  

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#15]
سفارشات در وضعيت بسته شده را نيز مي توان صورت حساب نمود .در صورتيكه در سيستم براي سفارش شماره 127 كه تائيد نهايي شده و بسته شده امكان صدور صورت حساب وجود ندارد .(شركت حافظ)

**Comment by hatefi-arman** [comment]
Problem resolved and is ready to use.
Duration 2:30'
