### ISSUE TITLE
سریالهای تایید نهایی نشده در سیستم جامع سوخت

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#2]
1-سریال 273 شرکت تامین کننده 1760
 2-سریال 279 فرمانده ص90.042
3-سریال 270 خطا
5-سریال 267 فرمانده 48.570. درسته 
6-سریال 252 تامین کننده  1760
7-سریال 248 فرمانده 499.055 درسته
8-سریال 262 فرمانده در499.145
9- سریال 269 فرمانده 199.751 
10-سریال 265 فرمانده 200.614
11-سریال 253 تامین کننده 1760
12 –سریال 255 تامین کننده 1760
13- سریال 235 تامین کننده 1760
14-سریال 215 فرمانده 299.272
15 –سریال 266 فرمانده 1297.73 
16-سریال 217 فرمانده 200.546
17-سریال 278 فرمانده 650.376
18-سریال 275 فرمانده 1501.339

**Comment by hatefi-arman** [comment]
بررسی خطاها با سرکار خانم مهاجر
Duration 1:00'

**Comment by hatefi-arman** [comment]
Inovoice No. :  273 & relevant Order :    Completed 
Inovoice No. :  252 & relevant Order :    Completed 
Inovoice No. :  253 & relevant Order :    Completed 
Inovoice No. :  255 & relevant Order :    Completed 
Inovoice No. :  235 & relevant Order :    Completed 

Duration: 1:00'

**Comment by hatefi-arman** [comment]
- Decision Making for discrepancy between receipts and invoiced quantities.
- Maintenance Mrs. Mohajer 
  Duration: 0:45'
