### ISSUE TITLE
تصمیم گیری در خصوص اختلاف بین میزان سوخت گیری و مقدار صورتحساب شده

### ISSUE THREAD

**Issue by hatefi-arman** [ehsmohammadi/Fuel-Management-Support#36]
Ref to Issue #2 , some discrepancies found in Receipt quantity and Invoiced Quantity, which requires decision.

**Comment by Rezaeian** [comment]
چنانچه امكان تصحيح رسيد هاي انبار و ركوردهاي  گزارش سوخت وجود دارد ، مقادير با توجه به رقم صورت حساب اصلاح گردد
