### ISSUE TITLE
revert data for record 75875

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#38]
خواهشمند است اطلاعات ثبت شده براي ركورد 75875 برگشت داده شود . كشتي به اشتباه عمليات سوخت گيري را به عنوانCorrection  ثبت نموده است 
![tuutyutyutyu](https://cloud.githubusercontent.com/assets/3368702/15466857/d6deb47e-20f0-11e6-831f-cc9b6c85015a.png)

**Comment by hatefi-arman** [comment]
موضوع فوق در #34  شرح داده شده است.
