### ISSUE TITLE
عدم مشاهده گزارشات کشتی کیازند

### ISSUE THREAD

**Issue by hatefi-arman** [ehsmohammadi/Fuel-Management-Support#42]
کارشناس عملیات کشتی کیازند اطلاع رسانی نموده اند که گزارشات این کشتی به طور ناقص در سیستم سوخت جذب گردیده است.

**Comment by hatefi-arman** [comment]
با بررسی گزارشات موجود در پایگاه **EventReport** لیست گزارشات دریافت شده برای ماه 4 سال 2016 به شرح ذیل می باشد.
![image](https://cloud.githubusercontent.com/assets/5567997/15468993/9e1ecc26-20fc-11e6-9e6c-69aec301735c.png)
ضمناً برای ماه 5 از سال 2016 گزارشی در پایگاه  مذکور دریافت نگردیده است.
می بایست مسیر ارتباطی کشتی با شرکت مورد بررسی قرار گیرد.

Duration: 0:45'

**Comment by Rezaeian** [comment]
گزارشات توسط كشتي با فرمت اشتباه ارسال ميگرديد كه با صحبت با فرمانده كشتي قرار شد اطلاعات با فرمت درست ارسال گردد
