### ISSUE TITLE
 Charter in end خطا در زمان تائيد ركورد 

### ISSUE THREAD

**Issue by Rezaeian** [ehsmohammadi/Fuel-Management-Support#52]
براي كشتي همگام با خطا مواجه مي شويم . با توجه به اينكه كليه عمليات انبارداري براي كشتي مورد نظر قيمت گذاري و سند شده است خواهشمند است علت خطاي مورد نظر بررسي گردد  charter in end  در زمان تاديد ركورد

**Comment by hatefi-arman** [comment]
مبالغ مربوطه می بایست به دلار وارد گردد.
@Rezaeian

**Comment by hatefi-arman** [comment]
رکورد مربوطه مجددا دارای خطا شد.
علت آن ناشی از برگشت نادرست رکورد های انبار در زمانی که دسترسی به پایگاه داده باز بود، شناخته شد. 
پس از رفع خطا ، خطای دیگری در زمان انجام قیمت گذاری رکورد های انبار ملا حظه گردید که منجر به مسئله جدیدی شد که در گیت هاب وارد شد.
Duration : 1:30'
