### ISSUE TITLE
Daryakaran-Lahiji-SAPID: ROD Following

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#82]

**Comment by ehsmohammadi** [comment]
Is follow and confirmed till 2016-07-13 , is stop by missing noon report in Date : 2016-07-14

**Comment by ehsmohammadi** [comment]
Since the captain could not send the missing noon report (wrong starting date two times ) , we must create that noon report and import it to system with missing consumption that we had deal with.

**Comment by ehsmohammadi** [comment]
Event report confirmed and  updated until 2016/08/31 ...

**Comment by ehsmohammadi** [comment]
Event report confirmed and updated until 2016/09/03 ...

**Comment by ehsmohammadi** [comment]
Event report confirmed and updated until 2016/09/04 ...

**Comment by ehsmohammadi** [comment]
updated till to day ..

**Comment by ehsmohammadi** [comment]
Missing noon report on 2016-09-07 ...

**Comment by ehsmohammadi** [comment]
New event report imported for 2016-09-07 with corrected ROB and consumption.

**Comment by ehsmohammadi** [comment]
updated till now

**Comment by SaeidBarzegar** [comment]
Updated till now

**Comment by ehsmohammadi** [comment]
Updated till now

**Comment by ehsmohammadi** [comment]
Reminder: probably dry dock voyage of Daryakaran will be ended at Sunday.
**check with Lahiji**

**Comment by SaeidBarzegar** [comment]
Dry dock was ended at 1395/07/06 (check end of voyage time with Ms.Lahiji) and we should create chartering process in IRISL account

**Comment by ehsmohammadi** [comment]
First of all : @SaeidBarzegar  tnx man , so pleased to work with you 
Refer to the phone conversation with Ms.lahiji Dry dock is ended in 2016-09026 at 17:00 
Departure report time was changed to 16:59 and end of voyage report inserted to system at 17:00 on above date , after that charter in and out is created in system and Ms.Mohajer must confirmed it

**Comment by ehsmohammadi** [comment]
Problem in charter out start , it said no voyage was issued ... problem in correction , 
Value of activation was wrong 
Now all thing in order an they can follow up their vessel
