### ISSUE TITLE
Revert data for Record 75875 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#9]
كشتي به اشتباه عمليات سوخت گيري را به عنوانCorrection  ثبت نموده است .

![asda](https://cloud.githubusercontent.com/assets/3368702/15153473/990eedf0-16ee-11e6-977d-0f7cd860e2f4.png)

**Comment by hatefi-arman** [comment]
عملیات مورد نظر انجام پذیرفت.
خواهشمند است اطلاعات جدید برای رکورد مورد نظر وارد پایگاه داده **EventReport** گردد.
SP های زیر برای اینکار تولید شدند:
RemoveTransactionItemPricesAndVouchers
RevertFuelReportInventoryOperationsAndFuelReportState
RevertFuelReportInventoryOperations
Duration: 1Day and 1:00
