### ISSUE TITLE
Delice-Lahiji : ROD Following

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/Fuel-Management-Support#97]

**Comment by ehsmohammadi** [comment]
Charter in and out end is inserted and rod following is needed ...

**Comment by ehsmohammadi** [comment]
Event report confirmation till 2016-09-04 is done  ....

**Comment by ehsmohammadi** [comment]
updated till today

**Comment by ehsmohammadi** [comment]
updated till today  but call Ms.Lahiji for be sure of ROB and consumption ..

**Comment by ehsmohammadi** [comment]
updated till today ..

**Comment by ehsmohammadi** [comment]
updated till now

**Comment by SaeidBarzegar** [comment]
Updated toll now

**Comment by ehsmohammadi** [comment]
Updated till now

**Comment by SaeidBarzegar** [comment]
Dry dock was ended an we should create chartering process in IRISL account

**Comment by ehsmohammadi** [comment]
updated till now

**Comment by ehsmohammadi** [comment]
updated till now

**Comment by ehsmohammadi** [comment]
has been updated till now

**Comment by ehsmohammadi** [comment]
fuel report has been updated till now

**Comment by ehsmohammadi** [comment]
fuel report has been updated till now

**Comment by ehsmohammadi** [comment]
fuel report has been updated till now

**Comment by ehsmohammadi** [comment]
fuel report was updated till now

**Comment by ehsmohammadi** [comment]
Fuel report updated till now

**Comment by ehsmohammadi** [comment]
End of voyage at date : 2016-10-28 11:48 was not valid
Dry dock voyage was ended at 2016-11-02 
End of voyage Rob :  
HFO: 536.6 
DOLS : 18

**Comment by ehsmohammadi** [comment]
All thing in order and delice charter in and our Start was inserted to system ,
 we will wait for Mr.Mohajer Confirmation

**Comment by ehsmohammadi** [comment]
Mr.mohajer did her job
